### PR TITLE
Update waifu.json

### PR DESCRIPTION
**Pull request by deusexcalamus**
Change Mugino Shizuri's sobriquet and add Othinus.

### CODE REVIEW

**Comment by dgw** [comment]
Hmm, I'm not sure about including LN characters just yet.

At any rate, Othinus appears in titles that are not exactly "Toaru Kagaku no Railgun", so to me it doesn't make sense to put her in this section.

**Comment by deusexcalamus** [comment]
> Hmm, I'm not sure about including LN characters just yet.
> 
> At any rate, Othinus appears in titles that are not exactly "Toaru Kagaku no Railgun", so to me it doesn't make sense to put her in this section.

Well, like...that's just your opinion, man. I'll edit it to move her to Index though.

**Comment by dgw** [comment]
It's also a fact that this database doesn't include manga or LN characters, only those from anime and a few video games. 🤷‍♂️

**Comment by dgw** [comment]
I'm leaving out the LN character. If those are going to be included, that's a whole project of its own. At that point I would split "games" and "books" into sub-lists, leaving just anime in the main JSON file.

**Pull request merged**
